#!/bin/bash

# Set up our environment
mkdir -p ~/Downloads/xkcd
cd ~/Downloads/xkcd

# Download the inital page and image
curl https://www.xkcd.com \
  | tee xkcd.txt \
  | grep embedding \
  | awk '{print $5}' \
  | xargs wget

# Set up the caption
FILE=$(cat xkcd.txt \
  | grep title \
  | grep img \
  | awk '{print $2}' \
  | awk 'BEGIN{FS="/"}{print $5}' \
  | tr -d \")

# Grab the caption
cat xkcd.txt \
  | grep title \
  | grep img \
  | awk 'BEGIN{FS="\""}{print $4}' > ${FILE}.txt

# Clean Up
rm xkcd.txt
