#!/bin/bash
INPUT=$(echo $1 | sed 's/ /\\ /g')
DIR=$(readlink -f "$1")
DIRNAME=$(echo "${DIR}" |awk 'BEGIN{FS="/"}{print $(NF)}' | sed 's/ /_/g')

DATE=$(date +%Y_%m_%d)
DBDIR=/home/james/Downloads/xfer/home/${DATE}
TMPDIR=/tmp/${DATE}.home

PARFILE=${TMPDIR}/${DIRNAME}.par2
RARFILE=${TMPDIR}/${DIRNAME}.rar
TGZFILE=${TMPDIR}/${DIRNAME}.tar.gz
#GPGFILE=${TMPDIR}/${DIRNAME}.tar.gz.gpg



mkdir -p ${TMPDIR}
tar -cvzf "${TGZFILE}" --directory="${DIR}" .
#gpg -e -R 3A3800D7B0682446 -o "${GPGFILE}" "${TGZFILE}"
#rar a -v10M -ep "${RARFILE}" "${GPGFILE}"
rar a -v10M -ep "${RARFILE}" "${TGZFILE}"
par2create "${PARFILE}" "${TMPDIR}"/*.rar


mkdir -p ${DBDIR}
#echo ${FILEINFO} > ${DBDIR}/filelist.txt
mv  ${TMPDIR}/*.par2 ${TMPDIR}/*.rar ${DBDIR}
#FILEINFO=$(ls ${TMPDIR}/*.par2 ${TMPDIR}/../*.rar)
#rm "${TGZFILE}" "${GPGFILE}"
rm "${TGZFILE}"
cd ${DBDIR} && sha512sum *.rar > ${DBDIR}/filelist.0.dl
